DELETE http://localhost:3001/api/blogs/66b3d3d9bb03f923495c1426
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NmIzZDNkOGJiMDNmOTIzNDk1YzE0MWQiLCJpYXQiOjE3MjMwNjE3Njh9.Y4VlMHWaGzJUJRXm79ZdnNQSfpMZ6YQAvmCIfU_SH9U