POST http://localhost:3001/api/blogs/66baccf28f1b80e3dccc5d1c/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1Y2hhbmdhMzIxIiwiaWQiOiI2NmFmZDhiZWM1YmRiOGYxYjE5ZTkwODEiLCJpYXQiOjE3MjM1MTczMjV9.b4R03qk6XTMF7hOtmHTi8xul2-OfmDoziJd3yQ8KQIc

{
    "content": "Comentario de prueba 2"
}